# Assignment 05 - Population Analysis

## Author: Tihana Gray

This notebook analyses population differences between sexes by age in Ireland.

Libraries:

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # For plotting graphs

File paths:

In [53]:
notebook_path = r'C:\\Users\\tihan\\OneDrive\\Desktop\\ATU\\programming-for-data-analytics\\assignments\\assignment05-population.ipynb'
file_path = r'C:\\Users\\tihan\\OneDrive\\Desktop\\ATU\\programming-for-data-analytics\\assignments\\population_for_analysis.csv'

Loading dataset & overview:

In [54]:
df = pd.read_csv(file_path) # Reads the CSV file into a pandas DataFrame.
df.head() # Displays the first few rows of the DataFrame.

,Single Year of Age,Carlow County Council,Cavan County Council,Clare County Council,Cork City Council,Cork County Council,Donegal County Council,Dublin City Council,Dún Laoghaire Rathdown County Council,Fingal County Council,...,Monaghan County Council,Offaly County Council,Roscommon County Council,Sligo County Council,South Dublin County Council,Tipperary County Council,Waterford City & County Council,Westmeath County Council,Wexford County Council,Wicklow County Council
0,0,699.0,1006.0,1377.0,2283.0,4190.0,1797.0,6213.0,2457.0,4009.0,...,868.0,935.0,748.0,743.0,3544.0,1932.0,1340.0,1129.0,1792.0,1710.0
1,1,649.0,1004.0,1360.0,2284.0,4115.0,1881.0,5699.0,2437.0,3894.0,...,821.0,937.0,764.0,766.0,3673.0,1808.0,1266.0,1158.0,1724.0,1682.0
2,2,689.0,1061.0,1473.0,2306.0,4290.0,1971.0,5830.0,2489.0,4308.0,...,870.0,945.0,893.0,764.0,3734.0,1836.0,1329.0,1108.0,1835.0,1796.0
3,3,754.0,1085.0,1468.0,2294.0,4437.0,2074.0,5580.0,2613.0,4384.0,...,900.0,1009.0,859.0,825.0,3856.0,2048.0,1476.0,1148.0,1864.0,1862.0
4,4,745.0,1047.0,1505.0,2243.0,4620.0,2089.0,5624.0,2658.0,4422.0,...,873.0,1007.0,833.0,820.0,3870.0,2072.0,1390.0,1208.0,1941.0,1897.0

📚 References: 
- https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html
- https://www.geeksforgeeks.org/pandas/python-pandas-dataframe/

In [55]:
df.info() # Provides a concise summary of the DataFrame.
df.describe() # Generates descriptive statistics of the DataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 33 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Single Year of Age                     101 non-null    int64
 1   Carlow County Council                  101 non-null    float64
 2   Cavan County Council                   101 non-null    float64
 3   Clare County Council                   101 non-null    float64
 4   Cork City Council                      101 non-null    float64
 5   Cork County Council                    101 non-null    float64
 6   Donegal County Council                 101 non-null    float64
 7   Dublin City Council                    101 non-null    float64
 8   Dún Laoghaire Rathdown County Council  101 non-null    float64
 9   Fingal County Council                  101 non-null    float64
 10  Galway City Council                    101 non-null    float64
 11  Galway County Council                  101 non-null    float64
 12  Ireland                                101 non-null    float64
 13  Kerry County Council                   101 non-null    float64
 14  Kildare County Council                 101 non-null    float64
 15  Kilkenny County Council                101 non-null    float64
 16  Laois County Council                   101 non-null    float64
 17  Leitrim County Council                 101 non-null    float64
 18  Limerick City & County Council         101 non-null    float64
 19  Longford County Council                101 non-null    float64
 20  Louth County Council                   101 non-null    float64
 21  Mayo  County Council                   101 non-null    float64
 22  Meath County Council                   101 non-null    float64
 23  Monaghan County Council                101 non-null    float64
 24  Offaly County Council                  101 non-null    float64
 25  Roscommon County Council               101 non-null    float64
 26  Sligo County Council                   101 non-null    float64
 27  South Dublin County Council            101 non-null    float64
 28  Tipperary County Council               101 non-null    float64
 29  Waterford City & County Council        101 non-null    float64
 30  Westmeath County Council               101 non-null    float64
 31  Wexford County Council                 101 non-null    float64
 32  Wicklow County Council                 101 non-null    float64
dtypes: float64(32), int64(1)
memory usage: 26.2 KB

,Single Year of Age,Carlow County Council,Cavan County Council,Clare County Council,Cork City Council,Cork County Council,Donegal County Council,Dublin City Council,Dún Laoghaire Rathdown County Council,Fingal County Council,...,Monaghan County Council,Offaly County Council,Roscommon County Council,Sligo County Council,South Dublin County Council,Tipperary County Council,Waterford City & County Council,Westmeath County Council,Wexford County Council,Wicklow County Council
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,...,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,50.000000,613.544554,808.950495,1266.712871,2217.861386,3565.861386,1654.297030,5868.445545,2315.445545,3272.336634,...,646.415842,823.267327,695.633663,695.029703,2980.940594,1662.326733,1261.019802,952.683168,1622.960396,1543.079208
std,29.300171,306.958516,406.352344,608.585760,1121.260568,1819.709059,777.550083,3427.079989,1038.389777,1920.958809,...,319.105916,407.154636,322.614963,316.910222,1608.771816,777.912104,599.663956,474.335977,778.904422,792.008203
min,0.000000,3.000000,6.000000,14.000000,23.000000,25.000000,15.000000,64.000000,32.000000,21.000000,...,5.000000,4.000000,7.000000,10.000000,17.000000,10.000000,17.000000,6.000000,16.000000,8.000000
25%,25.000000,412.000000,582.000000,1058.000000,1518.000000,2620.000000,1407.000000,3409.000000,1796.000000,1732.000000,...,492.000000,606.000000,568.000000,583.000000,1803.000000,1301.000000,1000.000000,634.000000,1280.000000,1114.000000
50%,50.000000,713.000000,915.000000,1431.000000,2525.000000,3841.000000,1826.000000,5912.000000,2775.000000,3660.000000,...,732.000000,935.000000,794.000000,799.000000,3544.000000,1834.000000,1462.000000,1103.000000,1817.000000,1702.000000
75%,75.000000,835.000000,1143.000000,1758.000000,3103.000000,5072.000000,2285.000000,7914.000000,3054.000000,4863.000000,...,894.000000,1161.000000,957.000000,935.000000,4193.000000,2253.000000,1725.000000,1329.000000,2258.000000,2197.000000
max,100.000000,1045.000000,1343.000000,2029.000000,3677.000000,6116.000000,2632.000000,12366.000000,3739.000000,6350.000000,...,1072.000000,1397.000000,1100.000000,1089.000000,5428.000000,2581.000000,2094.000000,1561.000000,2709.000000,2744.000000

📚 References: 
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html

## Part 1: Write a Jupyter notebook that analyses the differences between the sexes by age in Ireland.

Lists to store results:

In [56]:
region_list = []
mean_list = []

In [57]:
for region in df.columns[1:]: # Looping over all columns except the first (which is 'Single Year of Age')
    mean_age = np.average(df['Single Year of Age'], weights=df[region]) # Calculates the weighted average age for the region.
    region_list.append(region)
    mean_list.append(mean_age)

📚 References: 
- https://numpy.org/doc/stable/reference/generated/numpy.average.html
- https://docs.python.org/3/tutorial/datastructures.html#more-on-lists
- https://www.geeksforgeeks.org/python/how-to-calculate-weighted-average-in-pandas/
- https://www.geeksforgeeks.org/pandas/different-ways-to-iterate-over-rows-in-pandas-dataframe/

In [58]:
weighted_mean_df = pd.DataFrame({'Region': region_list,'Weighted_Mean_Age': mean_list}) # Creates a new DataFrame with the results.
weighted_mean_df.head()

                  Region  Weighted_Mean_Age
0  Carlow County Council          38.274997
1   Cavan County Council          38.033511
2   Clare County Council          39.582165
3      Cork City Council          38.575414
4    Cork County Council          38.600991

📚 References: 
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html
- https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.ewm.html
- https://www.geeksforgeeks.org/python/python-pandas-dataframe-mean/